on:
  workflow_dispatch: {}
  push:
    tags: 
    - 'v*'
  pull_request:
    types: [opened, synchronize, reopened, labeled]

name: Sanity Tests
jobs:
  tests:
    runs-on:
    - self-hosted
    - linux

    if: |
      github.event_name != 'pull_request' || 
      contains(github.event.pull_request.labels.*.name, 'needs-e2e-sanity-tests') &&
      (github.event.action != 'labeled' || github.event.label.name == 'needs-e2e-sanity-tests') 

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
         go-version-file: "go.mod"

      - name: Set up CI system
        run:  sudo apt-get update && sudo apt-get install -y nfs-common netbase && sudo rpcbind

      - name: Run sanity tests
        env:
          ANEXIA_TOKEN:                     ${{ secrets.ANEXIA_TOKEN }}
          ANEXIA_STORAGE_SERVER_IDENTIFIER: ${{ secrets.ANEXIA_STORAGE_SERVER_IDENTIFIER }}
        run: sudo -E make test-sanity

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: csi-driver.log
          path: csi-driver.log
