on:
  workflow_dispatch: {}
  push:
    tags: 
    - 'v*'
  pull_request: {}

name: Sanity Tests
jobs:
  tests:
    runs-on:
    - self-hosted
    - linux
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
         go-version: '1.20'

      - name: Set up CI system
        run:  sudo apt-get update && sudo apt-get install -y nfs-common netbase && sudo rpcbind

      - name: Run sanity tests
        env:
          ANEXIA_TOKEN:                     ${{ secrets.ANEXIA_TOKEN }}
          ANEXIA_STORAGE_SERVER_IDENTIFIER: ${{ secrets.ANEXIA_STORAGE_SERVER_IDENTIFIER }}
        run: sudo -E make test-sanity

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
          name: csi-driver.log
          path: csi-driver.log
